### ISSUE TITLE
The loss of bounding box is SmoothL1Loss.

### ISSUE THREAD

**Issue by deeppower** [hdjang/mmdetection-hdjang#4]
Hi, @hdjang. I find the loss of bounding box is IoU loss according to this paper. But the config file shows the loss of bounding box is SmoothL1 loss.

**Comment by hdjang** [comment]
Hi, @deeppower 

Yeah, configurations in config file may not match the original configuration of the paper since I just simply configured the FSAF model in the actual model definition file for "fast prototyping". You can check actual loss used in the paper from the file where model is defined.
