### ISSUE TITLE
Is it correct to use same convolution layers for different scales' feature map in FSAF Head ?

### ISSUE THREAD

**Issue by TriLoo** [hdjang/mmdetection-hdjang#5]
I noticed that the calculation of anchor-free cls & reg preds used following codes:
```python
      def forward_single(self, x):
        cls_feat = x
        reg_feat = x
        for cls_conv in self.cls_convs:
            cls_feat = cls_conv(cls_feat)
        for reg_conv in self.reg_convs:
            reg_feat = reg_conv(reg_feat)
        
        cls_score = self.fsaf_cls(cls_feat)
        bbox_pred = self.relu(self.fsaf_reg(reg_feat))
        
        return cls_score, bbox_pred

    def forward(self, feats):
        return multi_apply(self.forward_single, feats)
```

where `multi_apply()` used the `map()` function to apply `forward_single()` to each `feature map` in `feats`. However the `self.cls_conv, self.reg conv` etc. should share their weights across different scale `feature map`, is this true ?

thanks

**Comment by hdjang** [comment]
Hi @TriLoo 

Yes, each detection head should share its weights across different levels of feature pyramid as noted in the original retinanet paper. FSAF also follows it.
